version: '3.7'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: docker-compose/Dockerfile
    image: sicna
    container_name: sicna-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sicna_network

  db:
    image: mysql:5.7
    container_name: sicna-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sicna_network

  nginx:
    image: nginx:1.17-alpine
    container_name: sicna-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sicna_network

  node:
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    container_name: sicna-node
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"


networks:
  sicna_network:
    driver: bridge
